### ISSUE TITLE
New V3 board getting a black screen on power on

### ISSUE THREAD

**Issue by MC6809E089** [SukkoPera/LittleSixteen#14]
Hi,

Sorry to raise this as an issue but I've just finished building a couple of V3 pcbs (one for me, one for my brother who can't solder so well), but neither board is working at the moment. I was wondering if there are any additonal instructions, or changes that need to be made to get a V3 board working, other than those written on the wiki? 

On power up, both boards exhibit the same behaviour: They output a black screen with sync to my retrotink mini, there is no other picture or sound. The boards supply voltages seem fine, 5.1V on the 5V rail, and 6.5V-ish for the tape motor, so I think they're okay. I believe I can see a clock signal, and some sort of activity on the data and address busses (I only have a bitscope, not a proper oscilliscope), and some of the chips on the board get warm after a while, but only warm, not too hot to touch or anything. I've tried the kernal version of 264 diagnostics ROM, and left it running to see if there was any audio, but nothing on screen or via the audio. I wondered if I might have gotten something wrong relating to the ROM/RAM jumpers.

The boards are configured for use with an original 8501 (lower socket), separate ROMs (all jumpers soldered to the left)  and 64k of RAM (both jumpers on the left). Do I need to do anything with JP1 or JP2?

All new components were sourced from Mouser in the US, and from the BOM linked in the BOM issue here. All original components were sourced from a pair working C16s, so that I had something to compare against. Because I built two pcbs, I've been able to swap all of the ICs between the two new boards and the original ones, and all ICs work fine in the original boards, so I believe the issue is somewhere on the new boards, either my bad soldering, or an incorrect component somewhere, rather than a failed one.

I understand that the problem is almost certainly something I've done, and could be pretty much anything but I thought I'd ask in case. Thanks in advance for any help or suggestions you can provide. :)

**Comment by SukkoPera** [comment]
First things that come to mind:
1. Make sure that all resistor networks are properly _bussed_ or _isolated_ as they should be.
2. Unsolder FB38/39/40. It's still unclear why but some people experience problems when using RC filters at these positions. If that works, you can replace them with ferrite beads.

**Comment by SukkoPera** [comment]
Glad you fixed it.

I don't think a 547 makes any difference wrt a 550. You have to work on the pots or even better remove the pots and just use the standard values as detailed here: https://github.com/SukkoPera/LittleSixteen/wiki/V3-Assembly-Notes#rf-modulator.
